// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuN3ed-Yso7_Rn1Ef6gSNrwhn_8PU0JMQ',
    appId: '1:1035856006398:android:8dbfb2614c407df70929af',
    messagingSenderId: '1035856006398',
    projectId: 'semarnarisemarang',
    storageBucket: 'semarnarisemarang.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCx_7tfUdQBrCvRxYCBDiZd-F34P5t54',
    appId: '1:1035856006398:web:e45fd98b7ec3ef770929af',
    messagingSenderId: '1035856006398',
    projectId: 'semarnarisemarang',
    authDomain: 'semarnarisemarang.firebaseapp.com',
    storageBucket: 'semarnarisemarang.firebasestorage.app',
    measurementId: 'G-08P57LLTBB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm36D-zLYKZPhEkzZa6ogyq2umD0SXtes',
    appId: '1:1035856006398:ios:be1d25702c76ae390929af',
    messagingSenderId: '1035856006398',
    projectId: 'semarnarisemarang',
    storageBucket: 'semarnarisemarang.firebasestorage.app',
    iosBundleId: 'com.example.semarnariApk',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm36D-zLYKZPhEkzZa6ogyq2umD0SXtes',
    appId: '1:1035856006398:ios:be1d25702c76ae390929af',
    messagingSenderId: '1035856006398',
    projectId: 'semarnarisemarang',
    storageBucket: 'semarnarisemarang.firebasestorage.app',
    iosBundleId: 'com.example.semarnariApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPCx_7tfUdQBrCvRxYCBDiZd-F34P5t54',
    appId: '1:1035856006398:web:f19b1d3c19b470cf0929af',
    messagingSenderId: '1035856006398',
    projectId: 'semarnarisemarang',
    authDomain: 'semarnarisemarang.firebaseapp.com',
    storageBucket: 'semarnarisemarang.firebasestorage.app',
    measurementId: 'G-1GK7FZXYEP',
  );

}